# Generated by Django 3.1 on 2020-08-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildings',
            old_name='names',
            new_name='name',
        ),
    ]
