# Generated by Django 3.1 on 2020-08-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200813_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildings',
            name='number_devices',
            field=models.CharField(default='', editable=False, max_length=3),
        ),
    ]
